services:
  - type: web
    name: kingimmob-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn kingimmob_backend:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
